### ISSUE TITLE
Download error: HTTP ERROR 403: Forbidden 

### ISSUE THREAD

**Issue by snayfach** [RyanCook94/inphared#12]
Hi Ryan - looks like some permissions may need to be updated:

> $ wget http://inphared.s3.climb.ac.uk/1Apr2022_data.tsv.gz
> --2022-04-02 13:53:32--  http://inphared.s3.climb.ac.uk/1Apr2022_data.tsv.gz
> Resolving inphared.s3.climb.ac.uk (inphared.s3.climb.ac.uk)... 137.205.52.6
> Connecting to inphared.s3.climb.ac.uk (inphared.s3.climb.ac.uk)|137.205.52.6|:80... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2022-04-02 13:53:33 ERROR 403: Forbidden.

Maybe the file is still updating and not live yet? I tried one other file from the April 1 release, which downloaded fine.

**Comment by snayfach** [comment]
The issue is that the 1Apr2022_data.tsv file is not compressed on your server. This works:
`wget http://inphared.s3.climb.ac.uk/1Apr2022_data.tsv`  

Is there a reason why the 1Apr2022_data.tsv file is not compressed while other files are?

**Comment by RyanCook94** [comment]
Hi Stephen,

Apologies about that! I'm currently away in the US and my supervisor who does the uploads to the S3 server is in UK. I wasn't sure if the files were being compressed before upload, so made the links in advance of their upload and guessed (I was wrong, ha).

Most of the links should be working now (those that aren't yet working are still being uploaded).

Thanks for flagging this for me.

All the best,
Ryan

**Comment by snayfach** [comment]
Can you please open permissions on `http://inphared.s3.climb.ac.uk/1Jun2022_genomes.fa`

**Comment by btredcup** [comment]
The permissions for the vConTACT2 annotations on the June update appear to be closed too.

**Comment by RyanCook94** [comment]
Hi @snayfach and @btredcup, thanks for flagging these. Seems something went wrong when uploading to our s3. They've since been re-uploaded and appear to be working at my end. Let me know if you're still unable though!

All the best,
Ryan

**Comment by btredcup** [comment]
Hi Ryan, some of the permissions for the August update are closed. 

All vConTACT files, 1Aug2022_refseq_genomes.fa and 1Aug2022_phages_downloaded_from_genbank.gb. 
Thanks

**Comment by RyanCook94** [comment]
Hi @btredcup, thanks for flagging this. Should all be good now, but let me know if not!

All the best,
Ryan

**Comment by btredcup** [comment]
Yes, all good now. Thanks Ryan
