### ISSUE TITLE
Oslovirus Escherichia phage TL-2011c is temperate phage

### ISSUE THREAD

**Issue by igortru** [RyanCook94/inphared#14]
you marked it as lytic.

just blast CDL18811.1 Integrase vs NC_019442

[misc_feature](https://www.ncbi.nlm.nih.gov/nuccore/NC_019442.1?from=1&to=1307)    complement(<1..1307)
                     /note="similar to integrase"

**Comment by RyanCook94** [comment]
Hi Igortu,

As part of the analysis for our paper, we tried to detect genes known to facilitate a temperate lifestyle using a well-described method. This was a high-throughput, bioinformatic estimate. Obviously, this method isn't perfect, but I was not able to manually inspect the annotations and literature of ~15,000 phage genomes.

**Comment by igortru** [comment]
Hi, Ryan!
I am working in NCBI and developing project VERY similar to yours:
https://ftp.ncbi.nlm.nih.gov/genomes/Viruses/PH.26.asn

it can be navigated using NCBI GenomeWorkbench.
I have added your data to my tree  as attributes and compare results.

I have found this genome using very simple method, Oslovirus is temperate genus,
if some genome is not temperate - just check it.
