### ISSUE TITLE
Weird characters in 1Aug2022_data.tsv

### ISSUE THREAD

**Issue by snayfach** [RyanCook94/inphared#16]
I ran into the following error when parsing the latest data.tsv file in python: 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 520: invalid continuation byte

Which is caused by 2 genomes in the file. The first one is AB910602, Xanthomonas phage XacF1. The tsv file contains a special character directly after the genome name. Previous versions of INPHARED containing this genome did not have this issue.

**Comment by RyanCook94** [comment]
Hi Stpehen,

Yeah, something strange has happened on that line. Please could I have the accession for the other strange genome?

Will then try to get an updated file up today.

Many thanks and best wishes,
Ryan

**Comment by snayfach** [comment]
I'm not sure about the other identifier. It's somewhere around line 5932 in the file, but python crashes before printing the line.

**Comment by krzysieqq** [comment]
Any updates?

**Comment by RyanCook94** [comment]
Hi @snayfach and @krzysieqq, apologies for the delay. I've had a play with the file and have uploaded a new version (still the same URL). Please could you let me know how you get along with this?

All the best,
Ryan

**Comment by krzysieqq** [comment]
Thx for update. I've checked and everything seems to be fine. All the best for you, nice job!
