### ISSUE TITLE
Unable to download latest version of database (version: 2Nov2022)

### ISSUE THREAD

**Issue by cdeanj** [RyanCook94/inphared#18]
Hi Ryan,

I am unable to download the Nov. 2, 2022 version of the database. 

When I run the following command:
```
wget http://inphared.s3.climb.ac.uk/2Nov2022_data.tsv
```

I receive a 404 response  Any thoughts?

Thanks!
Chris

**Comment by briglo** [comment]
same issue here, looks like the s3 bucket has been moved or deleted(?)

**Comment by RyanCook94** [comment]
Hi @briglo and @cdeanj ,

We've had an issue with our s3 but this is now resolved. I've just updated the s3 links on the GitHub to have the latest files (1st December). If you still need the November data, please change the 1Dec in the filename to 2Nov.

All the best,
Ryan

**Comment by briglo** [comment]
Thanks Ryan (for both an awesome resource and speedy resolution).
