### ISSUE TITLE
connection timeout fail with data download

### ISSUE THREAD

**Issue by k6logc** [RyanCook94/inphared#20]
Hi Ryan, 

**Thank you for inphared!**

We've been trying since yesterday to pull the April files and we keep erroring out with below, any idea when the server will be up again? Or is there another place to download from?

_Connecting to millardlab-inphared.s3.climb.ac.uk (millardlab-inphared.s3.climb.ac.uk)|147.188.173.14|:443... failed: Connection timed out._

Thank you!

Best,
Kathryn

**Comment by RyanCook94** [comment]
Hi Kathryn,

No worries at all, you're very welcome!

Our CLIMB is undergoing maintenance this weekend and I think this might be the cause of issue. We're meant to be back online on Monday, so hopefully this will be resolved then but please let me know if not.

All the best,
Ryan

**Comment by k6logc** [comment]
Okay great, will check again on Monday, thank you Ryan!

**Comment by RyanCook94** [comment]
Hi Kathryn,

I just had a look and we should now be be back online! Please let me know if this isn't the case for you.

All the best,
Ryan

**Comment by k6logc** [comment]
Hi Ryan,

Sorry for the lag, Yes - it was working and we got them.
Thank you!

Best,
Kathryn

**Comment by RyanCook94** [comment]
Woohoo, glad to hear it!

All the best,
Ryan
