### ISSUE TITLE
NoSuchBucketADM_sharetx00000e9b2255cb6a0e415-0064c3a5c9-13cbcfd7-s3-bham13cbcfd7-s3-bham-s3

### ISSUE THREAD

**Issue by jiaojiaoguan** [RyanCook94/inphared#21]
Dear author：

Thank you for your work at phage. when I want to download "PHROGs HMMs for consistent annotation of genomes (see the new --PHROG optional flag)", There is a error:

`NoSuchBucketADM_sharetx00000e9b2255cb6a0e415-0064c3a5c9-13cbcfd7-s3-bham13cbcfd7-s3-bham-s3`

Can you help me solve it?

**Comment by RyanCook94** [comment]
Hey,

Sorry for the delay in getting back to you. We've moved things from one s3 bucket to another and I'd forgotten to update the link (thank you for flagging this).

I've updated the link in the ReadMe but you can also grab them here: https://millardlab-inphared.s3.climb.ac.uk/HMM_phrog.tar.gz

All the best,
Ryan
