### ISSUE TITLE
FLiP phages are missing from the database

### ISSUE THREAD

**Issue by apcamargo** [RyanCook94/inphared#22]
I just noticed that the FLiP phage is missing from INPHARED, is there any reason for that? I'm not sure if they are being excluded because of the query or the filtering process.

See below two complete genomes:
https://www.ncbi.nlm.nih.gov/nuccore/MF361639
https://www.ncbi.nlm.nih.gov/nuccore/MH617761

**Comment by RyanCook94** [comment]
Hi Antônio,

I've just had a look and the first genome ([MF361639](https://www.ncbi.nlm.nih.gov/nuccore/MF361639)) has been submitted with the designation VRL (this is in the top right corner, next to the date). Phages should have the designation PHG. If this is a phage you know, please could you email Igor Tolstoy at NCBI and he should be able to fix it (tolstoy@ncbi.nlm.nih.gov)

As for the second genome ([MH617761](https://www.ncbi.nlm.nih.gov/nuccore/MH617761)), this is a metagenome derived sequence and therefore has the ENV designation. INPHARED is predominantly cultured phages to verify the quality/completeness of the genome (although we do include the Lak megaphages as a rare exception to this).

I hope this answers your query but please let me know if not. And thank you for flagging this!

All the best,
Ryan

**Comment by apcamargo** [comment]
Thanks, @RyanCook94! This makes sense

**Comment by apcamargo** [comment]
Igor helped me on this :)

It seems that the GenBank record has been updated, so I guess we will see FLiP in the next release
