### ISSUE TITLE
get_closest_relatives.pl gives an error to rebuild the index 

### ISSUE THREAD

**Issue by pravinn** [RyanCook94/inphared#25]
Dear Inphared team,
Thank you for your support and guidance in data analysis of bacteriophages. I was trying to use the Inphared tool for performing analysis and used the latest database, fasta, etc files for analysis. I tried running the get_closest_relatives.pl but ended up with an error as below. 

------------- EXCEPTION -------------
MSG: file 0 [ /data/DB/inphared/inphared_2Jan2024/2Jan2024_genomes.fa ] has changed size 1723039923 -> . This probably means you need to rebuild the index.
STACK Bio::Index::Abstract::_check_file_sizes /data/apps/conda/envs/bioinfo/lib/perl5/site_perl/Bio/Index/Abstract.pm:526
STACK Bio::Index::Abstract::open_dbm /data/apps/conda/envs/bioinfo/lib/perl5/site_perl/Bio/Index/Abstract.pm:418
STACK Bio::Index::Abstract::new /data/apps/conda/envs/bioinfo/lib/perl5/site_perl/Bio/Index/Abstract.pm:162
STACK Bio::Index::AbstractSeq::new /data/apps/conda/envs/bioinfo/lib/perl5/site_perl/Bio/Index/AbstractSeq.pm:94
STACK toplevel /data/apps/inphared/get_closest_relatives.pl:227
-------------------------------------

The database and the genomes.fa are from the latest version (1Jan_2024). Please can you help and provide your suggestion to run the script successfully.

**Comment by pravinn** [comment]
Please can we get a quick response on this issue.

**Comment by RyanCook94** [comment]
Hi Pravin,

Please could you quickly show me the command you ran and screenshots of the directories where the files are?

All the best,
Ryan

**Comment by pravinn** [comment]
Command
perl /data/apps/inphared/get_closest_relatives.pl -q ../contigs.fasta -i /data/apps/inphared/ -f bacteriophage_match.fna > out_list

**Comment by pravinn** [comment]
<img width="947" alt="inphared_folder_path_files" src="https://github.com/RyanCook94/inphared/assets/1758385/d249fddb-0773-48da-9cff-0e3821f5427b">
<img width="950" alt="inphared_error" src="https://github.com/RyanCook94/inphared/assets/1758385/80331178-37f5-4163-9ef5-d3ca32db66be">

**Comment by RyanCook94** [comment]
Interesting. I would try deleting the database file:

`rm 1Jan2024_genomes.db`

Then save the below as a Perl script (let's name it create_fasta_db.pl)....


```
#!/usr/bin/perl

#Give Perl the modules to use. If one of these is not installed, the script will fail. However, Perl should print to the screen which one is missing.
use Bio::Index::Fasta;
use strict;

#Usage statement
my $usage = "Takes multifasta file and produces an indexed db for rapid lookup of seqs.\nUsage: perl create_fasta_db.pl output.db input.fa";
 
#Get the index name from the command
my $Index_File_Name = $ARGV[0] or die "$usage\n";

#Define the index name
my $inx = Bio::Index::Fasta->new(-filename => $Index_File_Name,
                                     -write_flag => 1);

#Produce the index from the fasta file
$inx->make_index(@ARGV[1]);
```

To run the above:

`perl create_fasta_db.pl 1Jan2024_genomes.db 1Jan2024_genomes.fa`

Then try running your command again!

All the best,
Ryan

**Comment by pravinn** [comment]
Hi Ryan,

Thank you for sharing the details. The command has worked and started performing analysis. Have a good day.
