### ISSUE TITLE
Minor errors inphared.pl

### ISSUE THREAD

**Issue by lxsteiner** [RyanCook94/inphared#4]
I've tried running the main script to build the databases and found some variable definitions which don't work on other machines. 

https://github.com/RyanCook94/inphared/blob/7c089590e3551a3ad23dd407fff6402461fa8684/inphared.pl#L60
For Mash 2.3 the binary is simply `mash` on my system after a clean install. Did you rename your binary to `mash.2` or maybe it's called like that from an older version? A possible workaround - partial matching or a simple ``if`` statement in case of a failed explicit match.

I changed all of these:
https://github.com/RyanCook94/inphared/blob/7c089590e3551a3ad23dd407fff6402461fa8684/inphared.pl#L69
https://github.com/RyanCook94/inphared/blob/7c089590e3551a3ad23dd407fff6402461fa8684/inphared.pl#L77
https://github.com/RyanCook94/inphared/blob/7c089590e3551a3ad23dd407fff6402461fa8684/inphared.pl#L85
to how you defined other path variables: ``my $<name>_path = `which $tool_<name>`;``
otherwise it obviously doesn't work out of the box ;)

So far it didn't complete successfully so I can't comment on the rest of the script. Have to iron out many conflicts with different perl versions and associated modules unfortunately (as is always the case haha). Been trying to get it running in a conda environment because of prokka, mash and the entrez utilities; the only perl recipe is for v5.26.2 and yours was written with 5.23 (and my local install is v5.18.2 lol). Still figuring a workaround, but will update if I encounter any other errors.

Thanks,
Leon

**Comment by RyanCook94** [comment]
Hi Leon,

Thank you so much for raising this. I can see that I've been an idiot and accidentally uploaded a slightly different version of the script which has the paths I use on the server I work on (whoops).

I've just uploaded the version which searches for the dependencies (e.g. esearch) if they're installed somewhere in the path (using a which command).

Adding an if statement for different versions of MASH also definitely a good idea. Will add this to the list!

As for Perl version, if you're able to update to v5.26.2, I think you should be able to use 5.23 when it's called in the script?

Thanks again for raising this. Will check which file I upload a bit more closely next time...

All the best,
Ryan
