### ISSUE TITLE
Full virus taxonomy

### ISSUE THREAD

**Issue by snayfach** [RyanCook94/inphared#5]
Thanks for the great resource! 

In the `data.tsv` file you provide taxonomy at the genus, sub-family, family, and realm ranks. It would be really helpful if you could provide information at the other ranks as well, including order, class, and phylum. I know you provide the full classification in a separate field, but it's hard to know which term within the classification corresponds to which rank.

**Comment by RyanCook94** [comment]
Hi Stephen,

Thanks for the kind words and the good idea. I've just updated the script and it now includes genus, sub-family, family, order, class, phylum, kingdom and realm as separate fields in the tsv output files.

If you're able to run the new version of the script, you should be able to access these fields. If not, I'll be updating the files available for download in the near future.

Thanks again and all the best,
Ryan
