### ISSUE TITLE
get_closest_relatives.pl --max parameter not set properly

### ISSUE THREAD

**Issue by lxsteiner** [RyanCook94/inphared#6]
Maybe I interpret this wrong but you set the `--max` flag so the user can determine the amount of hits that gets printed to stdout after the execution of the script -- is my interpretation of `Maximum number of results to be outputted.`.

However, what happens is that you select the nr of hits from your intermediate mash output:
https://github.com/RyanCook94/inphared/blob/26ac6d635d9e33a4499ef6fbb7dacebf79f30265/get_closest_relatives.pl#L146

which is then further subset by eliminating duplicate entries:
https://github.com/RyanCook94/inphared/blob/26ac6d635d9e33a4499ef6fbb7dacebf79f30265/get_closest_relatives.pl#L171-L172

which is why setting e.g. `--max 10` will not result in 10 results for my query being output.

A simple solution could be just informing the user how many intermediate results were duplicate entries thus why `--max 10` didn't give 10 different hits. Or don't subset `xtemp.txt` and instead use a counter defined by `$max` on the following print:
https://github.com/RyanCook94/inphared/blob/26ac6d635d9e33a4499ef6fbb7dacebf79f30265/get_closest_relatives.pl#L197

EDIT: or actually here already since downstream parsing is pointless if you've already reached the max count:
https://github.com/RyanCook94/inphared/blob/26ac6d635d9e33a4499ef6fbb7dacebf79f30265/get_closest_relatives.pl#L172

Cheers,
Leon

**Comment by RyanCook94** [comment]
Hi Leon,

Thanks for raising this.

Yes, completely right that if there are RefSeq entries in the output, the number of matches included in output will not be the same as the number set using the `--max` flag.

I see this script as being quite a "quick and dirty" way of getting matches and I personally use MASH distance cutoff to filter my results instead of number of matches. I'm sure I can edit it at some point to make this flag better but it's probably going to the very bottom of my to-do-list!

I hope you can get use out of the script as is but I do recommend using with discretion.

Thanks again for helpful feedback.

All the best,
Ryan

**Comment by lxsteiner** [comment]
Hi Ryan,

sure, it's not an issue to find a workaround, just wanted to alert to the futility of the flag.

On another note, I'm having an issue with the `-f` flag to retrieve FASTA sequences of matches. It's throwing the following error:

```
------------- EXCEPTION -------------
MSG: Can't open 'SDBM_File' dbm file '/media/5c679734-9376-4617-815c-d4bd4177b8b2/leon/projects/06/soft/1Nov_2021/1Nov2021_genomes.db' : No such file or directory
STACK Bio::Index::Abstract::open_dbm /home/leon/miniconda3/envs/inphared_env/lib/perl5/site_perl/5.22.0/Bio/Index/Abstract.pm:401
STACK Bio::Index::Abstract::new /home/leon/miniconda3/envs/inphared_env/lib/perl5/site_perl/5.22.0/Bio/Index/Abstract.pm:162
STACK Bio::Index::AbstractSeq::new /home/leon/miniconda3/envs/inphared_env/lib/perl5/site_perl/5.22.0/Bio/Index/AbstractSeq.pm:93
STACK toplevel get_closest_relatives.pl:227
-------------------------------------
```

which I find weird because `1Nov2021_genomes.db` is exactly where it should be. You are extracting the file's path from the folder location which was given by the `-i` flag. And it can't be that the path is wrong otherwise the script wouldn't be able to extract the mash outputs from the other files. The path is correct and the file is there. Checked and changed file readability permissions, but still same error.

Can you confirm this works on your side? I'm not familiar with this Bioperl module.

STACK Bio::Index::Abstract::open_dbm /home/leon/miniconda3/envs/inphared_env/lib/perl5/site_perl/5.22.0/Bio/Index/Abstract.pm:401    
refers to:
```
    387         # Open the dbm file
    388         if ($dbm_type eq 'DB_File') {
    389                 my $hash_inf = DB_File::HASHINFO->new();
    390                 my $cache = $self->cachesize();
    391                 my $ffactor = $self->ffactor();
    392                 if ($cache){
    393                         $hash_inf->{'cachesize'} = $cache;
    394                 }
    395                 if ($ffactor){
    396                         $hash_inf->{'ffactor'} = $ffactor;
    397                 }
    398                 tie( %$db, $dbm_type, $filename, $mode_flags, 0644, $hash_inf )
    399                   or $self->throw("Can't open '$dbm_type' dbm file '$filename' : $!");
    400         } else {
    401                 tie( %$db, $dbm_type, $filename, $mode_flags, 0644 )
    402                   or $self->throw("Can't open '$dbm_type' dbm file '$filename' : $!");
    403         }
```

**Comment by RyanCook94** [comment]
Hi Leon,

It could be that there's something wrong with the db file. These are very temperamental and often need to be remade. So what might work is saving the following as a Perl script....

```
#!/usr/bin/perl
# Make an index for one or more fasta files

my $usage = " create_fastadb.pl index_name fasta.file  \n" ;  


    use Bio::Index::Fasta;
    use strict;

    my $Index_File_Name = $ARGV[0] or die $usage; 
    my $inx = Bio::Index::Fasta->new(-filename => $Index_File_Name,
                                     -write_flag => 1);
    $inx->make_index(@ARGV[1]);
```

Remove the database file from your directory and then produce a new one, using the `1Nov2021_genomes.fa` as input with the above script. So usage would be something like `perl the_above_script.pl 1Nov2021_genomes.db 1Nov2021_genomes.fa` 

Please let me know if this does/doesn't work!

All the best,
Ryan

**Comment by lxsteiner** [comment]
The script above generates 2 files for me: `1Nov2021_genomes.db.dir` and `1Nov2021_genomes.db.pag` and none as only `1Nov2021_genomes.db` so when I run `get_closest_relatives.pl` there is generally an error:

`Use of uninitialized value $sequencedb in scalar chomp at ../soft/inphared/get_closest_relatives.pl line 90.`    
because it can't find only the .db file I suppose, and when I use the `-f` flag there's more:

```
------------- EXCEPTION -------------
MSG: Did not provide a valid Bio::PrimarySeqI object
STACK Bio::SeqIO::fasta::write_seq /home/leon/miniconda3/envs/inphared_env/lib/perl5/site_perl/5.22.0/Bio/SeqIO/fasta.pm:217
STACK toplevel ../soft/inphared/get_closest_relatives.pl:231
-------------------------------------
```

Cheers,
Leon

**Comment by RyanCook94** [comment]
Hi Leon,

Bizarre that the above script didn't work. It shouldn't produce 2 files `1Nov2021_genomes.db.dir` and `1Nov2021_genomes.db.pag`. It should only produce `1Nov2021_genomes.db`. As far as I know, the two files you're getting are not intermediate files when producing an index, so it's not as though the script is running properly and failing during (e.g. due to insufficient memory).

This is starting to suggest to me there may be something wrong with how Perl/BioPerl has been configured on your system.

All the best,
Ryan

**Comment by lxsteiner** [comment]
Hm, could be, I'll look into it. Though there aren't many options e.g. from working inside conda environments (due to Prokka and other dependencies) with Perl and Bioperl options, if globally installed versions also cause a version clash.

```
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-bioperl              1.6.924                       4    bioconda
perl-file-find-rule       0.34                    pl526_5    bioconda
perl-number-compare       0.03                    pl526_2    bioconda
perl-text-glob            0.11                    pl526_1    bioconda
perl-threaded             5.26.0                        0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
```

Could you please provide a list of all the exact versions of Perl and Bioperl modules that you use?

**Comment by RyanCook94** [comment]
Hi Leon,

I have `v5.26.1` installed globally but the main inphared.pl script calls `v5.23`

As for specific modules, they are as follows:

```
Getopt::Long 2.49
POSIX 1.76
Time::localtime 1.02
File::Find 1.34
Bio::SeqIO 1.007002
Bio::Index::Fasta 1.007002
List::MoreUtils 0.425
strict 1.11
warnings 1.37
File::Find::Rule 0.34
```

I hope this helps!

All the best,
Ryan
