### ISSUE TITLE
Phage lifestyle

### ISSUE THREAD

**Issue by snayfach** [RyanCook94/inphared#7]
Maybe outside the scope of the project here, but would be great to also provide users with the predicted lifestyle of the phage using something like BACPHILIP, PHACTS, phageAI, or DeePhage.

**Comment by RyanCook94** [comment]
Hi Stephen. Thanks for the suggestion. It's definitely something we've considered and you may see it in the future, but I don't have any immediate plans to add this (maybe in the New Year though, we'll see how busy I am... haha).

**Comment by snayfach** [comment]
I figured as much :)
